### ISSUE TITLE
Failure to render the stanford bunny model using standard stack-gl code

### ISSUE THREAD

**Issue by bsergean** [stackgl/headless-gl#18]
Here's a gist to my code (coffee-script) which seems pretty standard to me.

https://gist.github.com/bsergean/db3f500f05584fa3f2dc

There's the output image

![out](https://cloud.githubusercontent.com/assets/11857745/9484777/8bedec20-4b65-11e5-946c-5d4125c20f28.png)

Pasted here for convenience

    #!/usr/bin/env coffee

    PNG = require('pngjs').PNG
    fs = require('fs')

    bunny = require('bunny')
    normals = require('normals')
    Shader = require('gl-shader')
    camera = require('lookat-camera')()

    # Create context
    width  = 600
    height = 400
    gl = require("gl").createContext(width, height)

    # Create texture
    tex = gl.createTexture()
    gl.bindTexture(gl.TEXTURE_2D, tex)
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, width, height, 0, gl.RGBA, gl.UNSIGNED_BYTE, null)

    # Create frame buffer
    fbo = gl.createFramebuffer()
    gl.bindFramebuffer(gl.FRAMEBUFFER, fbo)
    gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, tex, 0)

    #
    # Clear screen to red
    #
    gl.clearColor(1.0, 0.0, 0.0, 1.0)
    gl.clear(gl.COLOR_BUFFER_BIT)

    #
    # Load the bunny
    #
    Geometry = require('gl-geometry')
    geometry = Geometry(gl)

    geometry.attr('aPosition', bunny.positions)
    geometry.attr('aNormal', normals.vertexNormals(
        bunny.cells
      , bunny.positions
    ))
    geometry.faces(bunny.cells)

    #
    # Using the look at camera
    #
    mat4 = require('gl-mat4')
    projection = mat4.create()
    model      = mat4.create()
    view       = mat4.create()

    vertShader = """
        attribute vec3 aPosition;

        uniform mat4 uProjection;
        uniform mat4 uModel;
        uniform mat4 uView;
        
        void main() {
          gl_Position = uProjection * uView * 
                        uModel * vec4(aPosition, 1.0);
        }
    """

    fragShader = """
        void main() {
          gl_FragColor = vec4(0.0, 0.0, 1.0, 1.0);
        }
    """

    shader = Shader(gl
      , vertShader
      , fragShader
    )

    update = (width, height) ->

        camera.target   = new Float32Array([0,  0,  0])
        camera.position = new Float32Array([20,  20,  20])
        view = camera.view(view)

        aspectRatio = width / height
        fieldOfView = Math.PI / 4
        near = 0.01
        far  = 100

        mat4.perspective(projection, fieldOfView, aspectRatio, near, far)

    render = (width, height) ->

        update(width, height)

        gl.viewport(0, 0, width, height)

        gl.enable(gl.DEPTH_TEST)
        gl.enable(gl.CULL_FACE)

        geometry.bind(shader)

        shader.uniforms.uProjection = projection
        shader.uniforms.uView = view
        shader.uniforms.uModel = model

        geometry.draw(gl.TRIANGLES)

    render(width, height)

    # Grab pixels and write output to out.png
    path = "out.png"

    pixels = new Uint8Array(width * height * 4)
    gl.readPixels(0, 0, width, height, gl.RGBA, gl.UNSIGNED_BYTE, pixels)

    png = new PNG({ width: width, height: height })

    for i in [0...pixels.length]
         png.data[i] = pixels[i]

    stream = fs.createWriteStream(path)
    png.pack().pipe stream

    stream.on 'close', () ->
        console.log("Image written: #{ path }")

    gl.destroy()

**Comment by mikolalysenko** [comment]
Currently headless-gl is pretty broken, but if you are a bit patient soon the new branch on headless-gl/angle will be open and should perform way better.

**Comment by bsergean** [comment]
Ah, that's good to hear, thanks for the heads up. Would it help to submit another gist in javascript that can be used to regress this pb, or should I just wait for the angle branch to be merged or ready and test myself ?

**Comment by bsergean** [comment]
I just realized that I wasn't creating a depth buffer: I fixed that but I'm still getting a bad render:
My initialization now looks like that:

    # Create context
    width  = 600
    height = 400
    gl = require("gl").createContext(width, height)

    # Create frame buffer
    framebuffer = gl.createFramebuffer()
    gl.bindFramebuffer(gl.FRAMEBUFFER, framebuffer)
    framebuffer.width = width
    framebuffer.height = height

    # Create texture
    texture = gl.createTexture()
    gl.bindTexture(gl.TEXTURE_2D, texture)
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, width, height, 0, gl.RGBA, gl.UNSIGNED_BYTE, null)
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR)
    framebuffer.texture = texture

    # Create depth buffer
    depthBuffer = gl.createRenderbuffer()
    gl.bindRenderbuffer(gl.RENDERBUFFER, depthBuffer)
    gl.renderbufferStorage(gl.RENDERBUFFER, gl.DEPTH_COMPONENT16, width, height)

    gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, texture, 0)
    gl.framebufferRenderbuffer(gl.FRAMEBUFFER, gl.DEPTH_ATTACHMENT,  gl.RENDERBUFFER, depthBuffer)

    e = gl.checkFramebufferStatus(gl.FRAMEBUFFER)
    if e isnt gl.FRAMEBUFFER_COMPLETE
        console.log('Framebuffer is incomplete', e.toString())
    else
        console.log('Framebuffer is alright')

**Comment by mikolalysenko** [comment]
Fixed in gl@2.0.0

**Comment by bsergean** [comment]
I tried to build gl@2.0.0, and after changing the way the gl is constructed I'm still getting a red image out. 

    gl = require("gl")(width, height) # new way to get a context

Now I wonder if my example is correct or not. Maybe that red image is what I'm supposed to get.

**Comment by mikolalysenko** [comment]
You don't need to create that framebuffer/renderbuffer anymore in the newest headless-gl.  Probably the issue with your demo is that you didn't set up a depth attachment.

**Comment by bsergean** [comment]
I'm a bit lost, I tried many combination and still no luck. I have some code that's using three.js and node-webgl that works well (but I'm trying to stop using node-webgl as it's quite complicated to install the dependencies on Linux + it's not elegant to do offscreen rendering using Xvfb). I tried swapping the node-webgl context with a headless-gl context and I'm still getting a white image with no polygons to be seen.

ps: I also noticed that GL extensions are not supported yet; I wonder if this could be problematic.
